[package]
name = "llkv-table"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
crossbeam-channel.workspace = true
llkv-btree.workspace = true
llkv-storage.workspace = true
rayon.workspace = true
rustc-hash.workspace = true
