[package]
name = "llkv-column-map"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
bitcode = "0.6.7"

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "column_map_bench"
harness = false
